config:
  network:
    protocol: http
    interface: 0.0.0.0
    websocket_port: 6091
    use_ipv4: true
    ssl:
      pem_certificate: /opt/kasm/current/certs/tls.crt
      pem_key: /opt/kasm/current/certs/tls.key
      require_ssl: true
    udp:
      public_ip: auto

kasmDefaultConfig:
  securityContext:
  ingressRoute:
    entryPointName: "websecure"
    certificate:
      # defaults to the service name + -cert
      name:
      clusterIssuer: letsencrypt
  image:
    repository: "kasmweb/ubuntu-focal-desktop"
    tag: "1.13.0"
    pullPolicy: "IfNotPresent"
  podSecurityContext:
  replicaCount: 1
  service:
    port: 6901
    externalPort: 6901
  resources:
    requests:
      cpu: 400m
      memory: 1024Mi
  extraEnv:
    KASM_SVC_GAMEPAD: 0
    KASM_SVC_AUDIO_INPUT: 0
    KASM_SVC_UPLOADS: 0

services:
#  firstuser:
#    ingressRoute:
#      # -- Required
#      domain: test
#    extraEnv:
#      # -- Required
#      VNC_PW: test