{{- with .Values.disallowEmptyIngressHost -}}
  {{- if eq .enabled true -}}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-empty-ingress-host
  annotations:
    policies.kyverno.io/title: Disallow empty Ingress host
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Ingress
    policies.kyverno.io/description: >-
      An ingress resource needs to define an actual host name
      in order to be valid. This policy ensures that there is a
      hostname for each rule defined.
spec:
  background: false
  rules:
    - name: disallow-empty-ingress-host
      match:
        any:
          - resources:
              operations:
                - CREATE
                - UPDATE
              kinds:
                - Ingress
      {{- with .excludeNamespaces }}
      exclude:
        any:
        {{- range $exemption := . }}
          - resources:
              kinds:
                - Ingress
              name:
                - {{ tpl $exemption.name $ | quote }}
              namespace:
                - {{ tpl $exemption.namespace $ | quote }}
        {{- end }}
      {{- end }}
      validate:
        failureAction: Enforce
        message: "The Ingress host name must be defined, it is not allowed to be empty."
        deny:
          conditions:
            all:
              - key: "{{ `{{` }} request.object.spec.rules[].host || `[]` | length(@) {{ `}}` }}"
                operator: NotEquals
                value: "{{ `{{` }} request.object.spec.rules[].http || `[]` | length(@) {{ `}}` }}"
  {{- end -}}
{{- end }}