{{- with .Values.enforceSecurityContext }}
{{- if .enabled }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{.name}}
  annotations:
    policies.kyverno.io/title: Enforce security settings for pods
    policies.kyverno.io/category: Pod Security
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/minversion: 1.9.0
    pod-policies.kyverno.io/autogen-controllers: none
    policies.kyverno.io/description: >-
      Enforce security settings for pods
spec:
  background: false #Cannot mutate already existing pods
  useServerSideApply: true
  rules:
    - name: add-pod-security-context
      match:
        resources:
          operations:
            - CREATE
            - UPDATE
          kinds:
            - Pod
      {{- if .excludeNamespaces}}
      exclude:
        resources:
          namespaces:
           {{- range .excludeNamespaces }}
            - {{ . }}
           {{- end }}
      {{- end }}
      mutate:
        foreach:
          - list: "request.object.spec.containers[]"
            patchStrategicMerge:
              metadata:
                annotations:
                  +(clusterpolicies.kyverno.io/add-pod-security-context): Added securityContext to pod, container and initContainer
              spec:
                securityContext:
                  +(runAsNonRoot): true
                  +(runAsUser): 1001
                  +(runAsGroup): 1001
                  seccompProfile:
                    +(type): RuntimeDefault
                containers:
                  - (name): '*'
                    securityContext:
                      +(allowPrivilegeEscalation): false
                      +(capabilities):
                        drop:
                          - ALL
                      +(privileged): false
                initContainers:
                  - (name): '*'
                    securityContext:
                      +(allowPrivilegeEscalation): false
                      +(capabilities):
                        drop:
                          - ALL
                      +(privileged): false
                ephemeralContainers:
                  - (name): '*'
                    securityContext:
                      +(allowPrivilegeEscalation): false
                      +(capabilities):
                        drop:
                          - ALL
                      +(privileged): false
---
{{- end }}
{{- end }}