{{ with .Values.disallowUnsignedImages }}
{{ if .enabled }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{ .name }}
  annotations:
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Pod
    pod-policies.kyverno.io/autogen-controllers: {{ .autogenControllers }}
    policies.kyverno.io/category: DockerImage
    policies.kyverno.io/title: Disallow Unsigned Images
    policies.kyverno.io/description: >-
      Images needs to be signed with a specific private cosign key
spec:
  validationFailureAction: {{ .validationAction }}
  background: {{.background}}
  rules:
    - name: "{{ .name }}-rule"
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              namespaces:
              {{- range .excludeNamespaces }}
                - {{ . }}
              {{- end }}
      verifyImages:
      {{- range .imagesAndPublicKeyPairs }}
        - imageReferences:
            - {{ .image | quote}}
          attestors:
            - count: 1
              entries:
                - keys:
                    publicKeys: |-
{{ .key | indent 22 }}
      {{- end }}
{{ end }}
{{ end }}