{{- with .Values.enforceSecurityContext }}
{{- if .enabled }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{.name}}
  annotations:
    pod-policies.kyverno.io/autogen-controllers: {{ .autogenControllers }}
    policies.kyverno.io/title: Enforce security settings for pods
    policies.kyverno.io/category: Pod Security
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/minversion: 1.9.0
    policies.kyverno.io/description: >-
      Enforce security settings for pods
spec:
  rules:
    - name: add-pod-security-context
      match:
        resources:
          kinds:
            - Pod
      exclude:
        resources:
          namespaces:
              {{- range .excludeNamespaces }}
            - {{ . }}
              {{- end }}
      mutate:
        foreach:
          - list: "request.object.spec.containers[]"
            patchStrategicMerge:
              spec:
                securityContext:
                  +(runAsNonRoot): true
                  +(runAsUser): 999
                  +(runAsGroup): 1000
                  +(fsGroup): 2000
                  +(supplementalGroups): [ 9001 ]
                  seccompProfile:
                    +(type): RuntimeDefault
                containers:
                  - (name): '*'
                    securityContext:
                      +(allowPrivilegeEscalation): false
                      +(capabilities):
                        drop:
                          - ALL
                      +(privileged): false
                initContainers:
                  - (name): '*'
                    securityContext:
                      +(allowPrivilegeEscalation): false
                      +(capabilities):
                        drop:
                          - ALL
                      +(privileged): false
---
{{- end }}
{{- end }}