{{ with .Values.policyException }}
{{ if .enabled }}
apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: argocd-repo-server
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
spec:
  exceptions:
    - policyName: restrict-seccomp-strict
      ruleNames:
        - check-seccomp-strict
        - autogen-check-seccomp-strict
    - policyName: restrict-seccomp
      ruleNames:
        - check-seccomp
        - autogen-check-seccomp
    - policyName: enforce-security-context
      ruleNames:
        - add-pod-security-context
  match:
    any:
      # Exclude argocd-repo-server, otherwise this error occurs: "getaddrinfo() thread failed to start"
      - resources:
          kinds:
            - Deployment
            - ReplicaSet
            - Pod
          namespaces:
            - {{ $.Release.Namespace }}
          names:
            - argocd-repo-server*
{{- end }}
{{- end }}