{{- if .Values.backup.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{.Release.Name}}-backup-init
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    checksum/config: {{ include (print $.Template.BasePath "/backup/config.yaml") . | sha256sum | substr 0 50 }}
spec:
  backoffLimit: 0
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: {{.Release.Name}}-backup-init
    spec:
      tolerations: {{ .Values.backup.tolerations | toYaml | nindent 8  }}
      nodeSelector: {{ .Values.backup.nodeSelector | toYaml | nindent 8 }}
      restartPolicy: Never
      containers:
        - name: {{.Release.Name}}-backup-init
          image: {{ .Values.backup.image.repository }}:{{ .Values.backup.image.tag }}
          imagePullPolicy: IfNotPresent
          command: ['/bin/sh', '-c']
          args: ["/backup-config/configure-backup.sh"]
          volumeMounts:
            - name: backup-config
              mountPath: /backup-config
            - name: elasticsearch-certificate
              mountPath: /es-cert
          env:
            - name: ELASTICSEARCH_USERNAME
              value: elastic
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: elastic
                  name: {{ .Release.Name }}-es-elastic-user
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            runAsUser: {{ .Values.backup.image.userId }}
      volumes:
        - name: backup-config
          configMap:
            name: {{.Release.Name}}-backup-config
            defaultMode: 0755
        - name: elasticsearch-certificate
          secret:
            secretName: {{ .Release.Name }}-es-http-certs-public
      securityContext:
        fsGroup: 1001
        runAsGroup: 1002
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
        runAsUser: {{ .Values.backup.image.userId }}
{{- end }}
