{{- with .Values.externalSecret }}
{{- if and .enabled .pull.enabled }}
{{ $spec := .pull.spec  }}
{{- range $secretName, $secretConfig := .pull.secrets }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $secretName }}
spec:
  refreshInterval: {{ $spec.refreshInterval }}
  target:
    name: {{ $secretName }}
    creationPolicy: {{ $spec.creationPolicy }}
    deletionPolicy: {{ $spec.deletionPolicy }}
    {{- if .template }}
    template:
      engineVersion: v2
      type: {{ .type | default "Opaque" }}
      {{- with .template.metadata }}
      metadata:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .template.data }}
      data:
        {{- range $key, $tpl := .template.data }}
        {{ $key }}: {{ $tpl | quote }}
        {{- end }}
      {{- end }}
      {{- if .template.templateFrom }}
      templateFrom:
        {{- toYaml .template.templateFrom | nindent 8 }}
      {{- end }}
    {{- end }}
  secretStoreRef:
    kind: {{ $.Values.externalSecret.secretStore.kind }}
    name: {{ $.Values.externalSecret.secretStore.name }}
  data:
  {{- range $secretConfig.keys }}
    - secretKey: {{ .name | quote }}
      remoteRef:
        key: {{ required "Path to pull secret is required" $secretConfig.path | quote }}
        property: {{ .remoteKey | default .name | quote }}
        conversionStrategy: {{ $secretConfig.conversionStrategy | default $spec.conversionStrategy }}
        decodingStrategy: {{ $secretConfig.decodingStrategy | default $spec.decodingStrategy }}
        metadataPolicy: {{ $secretConfig.metadataPolicy | default $spec.metadataPolicy }}
  {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
