{{- with .Values.externalSecret }}
{{- if and .enabled .generators.enabled .generators.passwords }}
{{- range $name, $config := .generators.passwords }}
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: {{ $name }}
  annotations:
    argocd.argoproj.io/sync-wave: "11"
spec:
  {{- $config.spec | toYaml | nindent 2 }}
---
{{- end }}
{{- end }}
{{- end }}
