apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name:  {{ .Values.ingressRoute.certificate.name }}
spec:
  secretName: {{.Values.ingressRoute.certificate.name }}
  issuerRef:
    name: {{.Values.ingressRoute.certificate.clusterIssuer}}
    kind: ClusterIssuer
  commonName: {{.Values.ingressRoute.domain}}
  privateKey:
    algorithm: "RSA"
    size: 4096
  dnsNames:
    - {{.Values.ingressRoute.domain}}