apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name:  {{ .Values.ingressRoute.certificate.name | default .Release.Name }}
spec:
  secretName: {{.Values.ingressRoute.certificate.name}}
  issuerRef:
    name: {{.Values.ingressRoute.certificate.clusterIssuer}}
    kind: ClusterIssuer
  commonName: {{.Values.nextcloud.nextcloud.host}}
  privateKey:
    algorithm: "RSA"
    size: 4096
  dnsNames:
    - {{.Values.nextcloud.nextcloud.host}}