apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}
spec:
  entryPoints:
    - {{.Values.ingressRoute.entryPointName}}
  routes:
    - kind: Rule
      match: Host(`{{ .Values.ingressRoute.domain }}`)
      services:
        - name: {{ .Release.Name }}
          passHostHeader: true
          port: {{.Values.nextcloud.service.port}}
  tls:
    secretName: {{.Values.ingressRoute.certificate.name }}
    domains:
      - main: {{ .Values.ingressRoute.domain}}
