{{- with .Values.externalSecret }}
{{- if and .enabled .pull.enabled }}
{{- $spec := .pull.spec | default dict }}
{{- $commonLabels := .commonLabels | default dict }}
{{- $commonAnnotations := .commonAnnotations | default dict }}
{{- $store := .secretStore | default dict }}
{{- range $secretName, $secretConfig := .pull.secrets }}
{{- $cfg := merge (dict) $secretConfig $spec }}
{{- if and (not $cfg.secretStoreRef) $store }}
{{- $_ := set $cfg "secretStoreRef" $store }}
{{- end }}
{{- include "common.externalSecrets.externalSecret" (dict "name" $secretName "config" $cfg "commonLabels" $commonLabels "commonAnnotations" $commonAnnotations) }}
{{- end }}
{{- end }}
{{- end }}
