{{- with .Values.externalSecret }}
{{- if and .enabled .generators.enabled .generators.passwords }}
{{- $commonLabels := .commonLabels | default dict }}
{{- $commonAnnotations := .commonAnnotations | default dict }}
{{- range $name, $config := .generators.passwords }}
{{- include "common.externalSecrets.passwordGenerator" (dict "name" $name "config" $config "commonLabels" $commonLabels "commonAnnotations" $commonAnnotations) }}
---
{{- end }}
{{- end }}
{{- end }}
