{{- with .Values.externalSecret }}
{{- if and .enabled .generators.enabled .generators.passwords }}
{{- range $name, $config := .generators.passwords }}
{{- include "common.externalSecrets.passwordGenerator" (dict "name" $name "config" $config) }}
---
{{- end }}
{{- end }}
{{- end }}
