{{- with .Values.externalSecret }}
{{- if and .enabled .push.enabled }}
{{- $spec := .push.spec | default dict }}
{{- $commonLabels := .commonLabels | default dict }}
{{- $commonAnnotations := .commonAnnotations | default dict }}
{{- $store := .secretStore | default dict }}
{{- range $secretName, $secretConfig := .push.secrets }}
{{- $cfg := merge (dict) $secretConfig $spec }}
{{- if and (not $cfg.secretStores) $store }}
{{- $_ := set $cfg "secretStores" (list $store) }}
{{- end }}
{{- include "common.externalSecrets.pushSecret" (dict "name" $secretName "config" $cfg "commonLabels" $commonLabels "commonAnnotations" $commonAnnotations) }}
---
{{- end }}
{{- end }}
{{- end }}
