{{- with .Values.externalSecret }}
{{- if and .enabled .push.enabled }}
{{- $spec := .push.spec | default dict }}
{{- range $secretName, $secretConfig := .push.secrets }}
{{- include "common.externalSecrets.pushSecret" (dict "name" $secretName "config" (merge (dict) $secretConfig $spec) "context" $) }}
---
{{- end }}
{{- end }}
{{- end }}
