apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: cert-manager-webhook-opentelekomcloud
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
spec:
  exceptions:
    - policyName: disallow-capabilities-strict
      ruleNames:
        - require-drop-all
    - policyName: disallow-privilege-escalation
      ruleNames:
        - privilege-escalation
    - policyName: require-run-as-nonroot
      ruleNames:
        - run-as-non-root
    - policyName: restrict-seccomp-strict
      ruleNames:
        - check-seccomp-strict
    - policyName: enforce-security-context
      ruleNames:
        - add-pod-security-context
  match:
    any:
      - resources:
          kinds:
            - Deployment
            - ReplicaSet
            - Pod
          names:
            - cert-manager-webhook-opentelekomcloud*
