apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: disallow-host-namespaces-exclusions
  namespace: kyverno
spec:
  exceptions:
    - policyName: disallow-host-namespaces
      ruleNames:
        - host-namespaces
  match:
    any:
      - resources:
          kinds:
            - Pod
          namespaces:
            - monitoring
          names:
            - prometheus-stack-prometheus-node-exporter*