apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: host-path-exclusions
  namespace: kyverno
spec:
  exceptions:
    - policyName: disallow-host-path
      ruleNames:
        - host-path
  match:
    any:
      - resources:
          kinds:
            - Pod
          namespaces:
            - monitoring
          names:
            - elastic-stack-filebeat*
            - prometheus-stack-prometheus-node-exporter*