apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: disallow-host-ports-exclusions
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
spec:
  exceptions:
    - policyName: disallow-host-ports
      ruleNames:
        - host-ports-none
  match:
    any:
      - resources:
          kinds:
            - Pod
          namespaces:
            - monitoring
          names:
            - prometheus-stack-prometheus-node-exporter*