apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: enforce-security-context-exclusions
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
spec:
  exceptions:
    - policyName: enforce-security-context
      ruleNames:
        - add-pod-security-context
  match:
    any:
      # Exclude argocd-repo-server otherwise this error occurs:  getaddrinfo() thread failed to start
      - resources:
          kinds:
            - Pod
          namespaces:
            - argocd
          names:
            - argocd-repo-server*
      - resources:
          kinds:
            - Pod
          namespaces:
            - kube-system