{{- with .Values.prometheusStack.ingress.grafana}}
{{- if .enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{$.Release.Name}}-grafana
  {{- with .labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .className | default "traefik" }}
  {{- if .tls }}
  tls:
    {{- range .tls }}
    {{- $certSecretName := .secretName | default (printf "%s-%s" $.Release.Name "cert")}}
    {{- if .hosts }}
    {{- range .hosts }}
    - hosts:
        - {{ tpl (toYaml .) $ }}
      secretName: {{ $certSecretName }}
    {{- end }}
    {{- end }}
    {{- end }}
  {{- end }}
  rules:
    {{- if .hosts }}
      {{- range .hosts }}
    - host: {{ tpl (toYaml .host) $ }}
      http:
        paths:
            {{- range .paths }}
          - path: {{ .path  }}
            pathType: {{ .pathType | default "Prefix"}}
            backend:
              service:
                name: {{$.Release.Name}}
                port:
                  number: {{ $.Values.prometheusStack.grafana.service.port }}
            {{- end }}
      {{- end }}
    {{- else }}
    - host: {{ tpl (toYaml .host) $ }}
      http:
        paths:
          - path: "/grafana"
            pathType: "Prefix"
            backend:
              service:
                name: {{$.Release.Name}}-grafana
                port:
                  number: {{ $.Values.prometheusStack.grafana.service.port }}
    {{- end }}
{{- end }}
{{- end }}