{{- if eq .Values.prometheusStack.ingress.grafana.className "traefik" }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix-{{ .Release.Name }}
spec:
  stripPrefix:
    prefixes:
      - "/grafana"
{{- end }}