{{- with .Values.middleware.ingress }}
{{- if .enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "llm-middleware.fullname" $ }}
  {{- with .labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .className | default "traefik" }}

  {{- if .defaultIngress.enabled | default true }}
  {{- $certSecretName := (.defaultIngress.tls).secretName | default (printf "%s-%s" (include "llm-middleware.fullname" $) "cert")}}
  tls:
    - hosts:
        - {{ tpl (toYaml .host) $ }}
      secretName: {{ $certSecretName }}
  rules:
    - host: {{ tpl (toYaml .host) $ }}
      http:
        paths:
          - path: {{ .defaultIngress.path | default "/" }}
            pathType: {{ .defaultIngress.pathType | default "Prefix"}}
            backend:
              service:
                {{- if (.defaultIngress.backend).name }}
                name: {{ tpl (toYaml .defaultIngress.backend.name) $ }}
                {{- else }}
                name: {{ default (include "llm-middleware.fullname" $)}}
                {{- end}}
                port:
                  {{- if ((.defaultIngress.backend).port).name }}
                  name: {{ tpl (toYaml .defaultIngress.backend.port.name) $ }}
                  {{- else }}
                  name: {{ default (include "llm-middleware.fullname" $)}}
                  {{- end}}
  {{- else }}

  {{- if .tls }}
  tls:
    {{- range .tls }}
    {{- $certSecretName := .secretName | default (printf "%s-%s" (include "llm-middleware.fullname" $) "cert")}}
    {{- if .hosts }}
    {{- range .hosts }}
    - hosts:
        - {{ tpl (toYaml .) $ }}
      secretName: {{ $certSecretName }}
    {{- end }}
    {{- end }}
    {{- end }}
  {{- end }}
  rules:
      {{- range .hosts }}
    - host: {{ tpl (toYaml .host) $ }}
      http:
        paths:
            {{- range .paths }}
          - path: {{ .path  }}
            pathType: {{ .pathType | default "Prefix"}}
            backend:
              service:
                {{- if (.backend).name }}
                name: {{ tpl (toYaml .backend.name) $ }}
                {{- else }}
                name: {{ default (include "llm-middleware.fullname" $)}}
                {{- end}}
                port:
                  {{- if ((.backend).port).name }}
                  name: {{ tpl (toYaml .defaultIngress.backend.port.name) $ }}
                  {{- else }}
                  name: {{ default (include "llm-middleware.fullname" $)}}
                  {{- end}}
            {{- end }}
      {{- end }}
  {{- end }}
{{- end }}
{{- end }}
