{{- if .Values.prometheusStack.grafana.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
spec:
  entryPoints:
    - {{.Values.ingressRoute.entryPointName}}
  routes:
    - kind: Rule
      match: Host(`{{.Values.ingressRoute.adminDomain}}`) && PathPrefix(`/grafana`)
      middlewares:
        - name: strip-prefix-{{ .Release.Name }}
          namespace: {{.Release.Namespace}}
      services:
        - kind: Service
          name: prometheus-stack-grafana
          namespace: {{.Release.Namespace}}
          passHostHeader: true
          port: 80
{{- end }}
