apiVersion: v2
dependencies:
  - name: traefik
    repository: oci://ghcr.io/traefik/helm
    version: 33.2.1
description: |
  The traefik ingress controller with some additional resources and sane default values for IITS projects. 
  Always read the [Changelog](Changelog.md) for information about possible migrations.
name: traefik
version: 33.2.1
appVersion: v3.2.5
