apiVersion: v2
appVersion: 10.22.0
dependencies:
  - name: traefik
    repository: https://helm.traefik.io/traefik
    version: 10.22.0
description: The traefik ingress controller with some additional resources and sane default values for IITS projects
name: traefik
version: 10.22.0-cleanup
