{{- with .Values.ingress }}
{{- if .enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "traefik.fullname" $ }}
  {{- with .labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .annotations }}
  annotations:
    iits-consulting.chart-creator/version: 1.0.10
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .className | default "traefik" }}

  {{- if .tls.enabled }}
  tls:
    - secretName: {{ .tls.secretName | default (printf "%s-%s" (include "traefik.fullname" $) "cert") }}
      hosts:
        - {{ .defaultHost }}
        {{- range $val := .additionalHosts }}
        - {{ $val }}
        {{- end }}
  {{- end }}

  rules:
      {{- range .rules }}
    - host: {{ tpl (toYaml .host) $ }}
      http:
        paths:
            {{- range .paths }}
          - path: {{ .path  }}
            pathType: {{ .pathType | default "Prefix"}}
            backend:
              service:
                {{- if (.backend).name }}
                name: {{ tpl (toYaml .backend.name) $ }}
                {{- else }}
                name: {{ default (include "traefik.fullname" $)}}
                {{- end}}
                port:
                  {{- if ((.backend).port).name }}
                  name: {{ tpl (toYaml ((.backend).port).name) $ }}
                  {{- else }}
                  name: "http"
                  {{- end}}
            {{- end }}
      {{- end }}
  {{- end }}
{{- end }}
