{{- if .Values.podMonitor.enabled }}
{{- with .Values.podMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "traefik.fullname" $ }}
  namespace: {{ template "traefik.namespace" $ }}
  {{- with .labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .annotations }}
  annotations:
    iits-consulting.chart-creator/version: 1.1.0
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik
  podMetricsEndpoints:
    - port: {{ .port }}
      interval: {{ .interval }}
      path: {{ .path }}
{{- end }}
{{- end }}