apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-internal
spec:
  type: ClusterIP
  ports:
{{- range $name,$spec := .Values.traefik.ports }}
{{- if ne $spec.expose true }}
    - port: {{ $spec.exposedPort }}
      targetPort: {{ $spec.port }}
      protocol: {{ $spec.protocol }}
      name: {{ $name }}
{{- end }}
{{- end }}
  selector:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: {{ .Release.Name }}