ingressRoute:
  domain: "my-domain.com"
  entryPointName: "websecure"
  certificate:
    name: "keycloak-gatekeeper-cert"
    clusterIssuer: letsencrypt
gatekeeper:
  replicaCount: 2
  automountServiceAccountToken: true
  extraVolumeMounts:
    - name: no-permission-link
      mountPath: /tmp
      readOnly: true
  extraVolumes:
    - name: no-permission-link
      configMap:
        name: no-permission-link
        defaultMode: 0777
  strategy:
    type: "RollingUpdate"
  config:
    discovery-url: "SET_BY_ARGOCD"
    client-id: keycloak-proxy-admin
    listen: 0.0.0.0:8080
    enable-refresh-tokens: false
    #internal https endpoint
    upstream-url: http://traefik-internal.routing.svc.cluster.local:8444
    upstream-timeout: 300s
    server-read-timeout: 300s
    server-write-timeout: 300s
    upstream-keepalive-timeout: 300s
    upstream-response-header-timeout: 300s
    upstream-expect-continue-timeout: 300s
    enable-json-logging: true
    enable-logging: false
    enable-default-deny: true
    enable-compression: true
    preserve-host: true
    enable-token-header: true
    enable-authorization-header: true
    enable-authorization-cookies: false