{{ with .Values.policyException }}
{{ if .enabled }}
apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: {{ $.Release.Namespace }}-{{$.Release.Name}}-op
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
spec:
  exceptions:
    - policyName: restrict-seccomp-strict
      ruleNames:
        - check-seccomp-strict
  match:
    any:
      - resources:
          kinds:
            - Pod
          names:
            - {{ $.Release.Name }}-?
          namespaces:
            - {{ $.Release.Namespace }}

{{- end }}
{{- end }}
