{{- with .Values.ollama.ingress }}
{{- if .enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ollama.fullname" $ }}
  {{- with .labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .className | default "traefik" }}
  {{- if .tls }}
  tls:
    {{- range .tls }}
    {{- $certSecretName := .secretName | default (printf "%s-%s" (include "ollama.fullname" $) "cert")}}
    {{- if .hosts }}
    {{- range .hosts }}
    - hosts:
        - {{ tpl (toYaml .) $ }}
      secretName: {{ $certSecretName }}
    {{- end }}
    {{- end }}
    {{- end }}
  {{- end }}
  rules:
      {{- if .hosts }}
      {{- range .hosts }}
    - host: {{ tpl (toYaml .host) $ }}
      http:
        paths:
            {{- range .paths }}
          - path: {{ .path  }}
            pathType: {{ .pathType | default "Prefix"}}
            backend:
              service:
                name: {{ include "ollama.fullname" $ }}
                port:
                  number: {{ default 8080 $.Values.ollama.service.port }}
            {{- end }}
      {{- end }}
    {{- else }}
    - host: {{ tpl (toYaml .host) $ }}
      http:
        paths:
          - path: "/{{ include "ollama.fullname" $ }}"
            pathType: "Prefix"
            backend:
              service:
                name: {{ include "ollama.fullname" $ }}
                port:
                  number: {{ default 8080 $.Values.ollama.service.port }}
    {{- end }}
{{- end }}
{{- end }}