{{- if .Values.ollama.persistentVolume.enabled -}}
{{- if not .Values.ollama.persistentVolume.existingClaim -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  {{- if .Values.ollama.persistentVolume.annotations }}
  annotations:
{{ toYaml .Values.ollama.persistentVolume.annotations | indent 4 }}
  {{- end }}
  labels:
    {{- include "ollama.labels" . | nindent 4 }}
  name: {{ template "ollama.fullname" . }}
spec:
  accessModes:
{{ toYaml .Values.ollama.persistentVolume.accessModes | indent 4 }}
{{- if .Values.ollama.persistentVolume.storageClass }}
{{- if (eq "-" .Values.ollama.persistentVolume.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.ollama.persistentVolume.storageClass }}"
{{- end }}
{{- end }}
{{- if .Values.ollama.persistentVolume.volumeMode }}
  volumeMode: "{{ .Values.ollama.persistentVolume.volumeMode }}"
{{- end }}
  resources:
    requests:
      storage: "{{ .Values.ollama.persistentVolume.size }}"
{{- end -}}
{{- end -}}