apiVersion: v1
kind: Service
metadata:
  name: {{ include "ollama.fullname" . }}
  labels:
    {{- include "ollama.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ollama.service.type }}
  ports:
    - port: {{ .Values.ollama.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ollama.selectorLabels" . | nindent 4 }}