{{- if .Values.ingress.kibana -}}
{{- with .Values.ingress.kibana }}
{{- if eq .enabled true }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Release.Name }}-kibana
  {{- with .labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
spec:
  {{ if .className }}
  ingressClassName: {{ .className }}
  {{- end }}

  tls:
    {{- tpl (.tls | toYaml) $ | nindent 4}}

  rules:
    - host: {{ .host }}
      http:
        paths:
          - path: {{ .path }}
            pathType: "Prefix"
            backend:
              service:
                name: {{ $.Release.Name }}-kb-http
                port:
                  name: "https"
{{- end }}
{{- end }}
{{- end }}
