{{ range $projectName,$project := .Values.projects }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $projectName }}
spec:
   project: {{ $projectName }}
   revisionHistoryLimit: 3
   syncPolicy:
     automated:
       prune: true
       selfHeal: true
       allowEmpty: true
     syncOptions:
       - CreateNamespace=true
       {{- if $project.serverSideApply}}
       - ServerSideApply=true
       {{- end}}
   destination:
     server: https://kubernetes.default.svc
     namespace: {{ $.Release.Namespace }}
   source:
     path: {{ $project.git.path | default $projectName }}
     repoURL: {{ $project.git.repoUrl }}
     targetRevision: {{ $project.git.branch | default "main" }}
     helm:
       values: |
          {{- $project.tofuValues | toYaml | nindent 10}}
       valueFiles:
         - values.yaml
         {{- if ($project.tofuValues).stage }}
         - values-{{ $project.tofuValues.stage }}.yaml
         {{- end}}
---
{{- end }}