{{ range $projectName,$project := .Values.projects }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ $projectName }}
spec:
  sourceRepos:
    - {{ $project.git.repoUrl }}
    {{- if $project.allowedUrls -}}
    {{- range $allowedUrl := $project.allowedUrls }}
    - {{ $allowedUrl }}
    {{- end }}
    {{ else }}
    - "*"
    {{- end }}
  destinations:
    - namespace: '*'
      server: 'https://kubernetes.default.svc'
  syncWindows:
  {{- range $syncWindow := default $.Values.global.syncWindow $project.syncWindow }}
    - {{ (tpl (toYaml $syncWindow) $) | nindent 6 -}}
  {{ end }}
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
{{- end }}
