apiVersion: batch/v1
kind: Job
metadata:
  name: {{.Release.Name}}-index-pattern-init
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "-5"
    checksum/config: {{ include (print $.Template.BasePath "/index-pattern-init/config.yaml") . | sha256sum | substr 0 50 }}
spec:
  backoffLimit: 0
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: {{.Release.Name}}-index-pattern-init
    spec:
      restartPolicy: Never
      containers:
        - name: {{.Release.Name}}-index-pattern-init
          image: {{ .Values.indexPatternInit.image.repository }}:{{ .Values.indexPatternInit.image.tag }}
          imagePullPolicy: IfNotPresent
          command: [ '/bin/sh', '-c' ]
          args: [ "/index-pattern-init-config/index-pattern-init.sh" ]
          volumeMounts:
            - name: index-pattern-init-config
              mountPath: /index-pattern-init-config
      volumes:
        - name: index-pattern-init-config
          configMap:
            name: {{.Release.Name}}-index-pattern-init-config
            defaultMode: 0755