apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webui.fullname" . }}
  labels:
    {{- include "webui.labels" . | nindent 4 }}
spec:
  {{- if not .Values.webui.autoscaling.enabled }}
  replicas: {{ .Values.webui.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "webui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.webui.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "webui.labels" . | nindent 8 }}
        {{- with .Values.webui.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.webui.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "webui.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.webui.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.webui.securityContext | nindent 12 }}
          image: "{{ .Values.webui.image.repository }}:{{ .Values.webui.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.webui.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.webui.service.port }}
              protocol: TCP
          env:
          {{- range $key, $value := .Values.webui.env }}
            - name: {{ printf "%s" $key | replace "." "_" | upper | quote }}
              value: {{ tpl $value $ | quote }}
            {{- end }}
          {{- if .Values.webui.envFromSecret}}
          envFrom:
            - secretRef:
                name: {{.Values.webui.envFromSecret}}
          {{- end }}
          {{- if .Values.webui.resources }}
          resources:
            {{- $limits := default dict .Values.webui.resources.limits }}
            {{- $ressources := merge .Values.webui.resources (dict "limits" $limits) }}
            {{- toYaml $ressources | nindent 12 }}
          {{- end}}
          {{- with .Values.webui.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.webui.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.webui.livenessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.webui.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.webui.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.webui.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.webui.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.webui.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.webui.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.webui.readinessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.webui.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.webui.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.webui.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.webui.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.webui.readinessProbe.failureThreshold }}
          {{- end }}
      volumes:
        {{- with .Values.webui.volumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.webui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webui.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.webui.tolerations }}
      tolerations:
        {{- with .Values.webui.tolerations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}