{{- if .Values.webui.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "webui.serviceAccountName" . }}
  labels:
    {{- include "webui.labels" . | nindent 4 }}
  {{- with .Values.webui.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.webui.serviceAccount.automount }}
{{- end }}
