{
 "title": "Blackbox Uptime Monitor",
 "tags": [
  "Blackbox",
  "Prometheus",
  "Uptime"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "baseline_correction_toggle", "label": "Baseline Correction", "query": "enabled : 1, disabled : 0" },
   {
    "name": "baseline",
    "label": "Baseline",
    "query": {
     "query": "label_values(probe_success,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instance Details",
   "type": "table",
   "description": "Show details about each active probe within the selected time range.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "probe_success", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Uptime Average (Auto Range)",
   "type": "table",
   "gridPos": { "h": 14, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (instance) (sum_over_time(clamp_max(probe_success - ignoring(instance,target, module) group_left () $baseline_correction_toggle*(probe_success{instance=\"$baseline\"}-1), 1.0)[$__range:30s] offset -1s))/sum by (instance) (count_over_time(probe_success[$__range:30s] offset -1s))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime Average",
   "type": "table",
   "gridPos": { "h": 14, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (instance) (sum_over_time(clamp_max(probe_success - ignoring(instance,target,module) group_left () $baseline_correction_toggle*(probe_success{instance=\"$baseline\"}-1), 1.0)[$__range:30s] offset -1s))/sum by (instance) (count_over_time(probe_success[$__range:30s] offset -1s))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime Average",
   "type": "table",
   "gridPos": { "h": 14, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (instance) (sum_over_time(clamp_max(probe_success - ignoring(instance,target,module) group_left () $baseline_correction_toggle*(probe_success{instance=\"$baseline\"}-1), 1.0)[$__range:30s] offset -1s))/sum by (instance) (count_over_time(probe_success[$__range:30s] offset -1s))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Timelines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Uptime Timeline (Auto Range)",
   "type": "state-timeline",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (instance) (sum_over_time(clamp_max(probe_success - ignoring(instance,target, module) group_left () $baseline_correction_toggle*(probe_success{instance=\"$baseline\"}-1), 1.0)[$__interval:30s] offset -1s))/sum by (instance) (count_over_time(probe_success[$__interval:30s] offset -1s))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime Timeline",
   "type": "state-timeline",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (instance) (sum_over_time(clamp_max(probe_success offset -1d1s - ignoring(instance,target,module) group_left () $baseline_correction_toggle*(probe_success{instance=\"$baseline\"} offset -1d1s -1), 1.0)[$__interval:30s]))/sum by (instance) (count_over_time(probe_success offset -1d1s [$__interval:30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime Timeline",
   "type": "state-timeline",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (instance) (sum_over_time(clamp_max(probe_success offset -1d1s - ignoring(instance,target,module) group_left () $baseline_correction_toggle*(probe_success{instance=\"$baseline\"} offset -1d1s -1), 1.0)[$__interval:30s]))/sum by (instance) (count_over_time(probe_success offset -1d1s [$__interval:30s]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}