apiVersion: v2
name: ext-postgres-operator
description: iits wrapper around movetokube/postgres-operator with ESO-driven RDS root credentials via the iits common chart.
type: application
version: 1.0.0
appVersion: "2.4.0"
dependencies:
  - name: ext-postgres-operator
    repository: https://movetokube.github.io/postgres-operator/
    version: 3.0.0
  - name: common
    repository: https://charts.iits.tech
    version: 0.3.1
