{{ range $diskTypeName,$diskTypeValues := .Values.diskType.evs }}
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  {{- if .Values.kmsId }}
  name: csi-disk-{{ $diskTypeName }}-{{ $diskTypeValues.reclaimPolicy }}-encrypted
  {{- else }}
  name: csi-disk-{{ $diskTypeName}}-{{ $diskTypeValues.reclaimPolicy }}
  {{- end }}
  annotations:
    storageclass.kubernetes.io/is-default-class: {{ default "false" $diskTypeValues.isDefault }}
parameters:
  csi.storage.k8s.io/csi-driver-name: disk.csi.everest.io
  csi.storage.k8s.io/fstype: ext4
  {{- if .Values.kmsId }}
  everest.io/crypt-key-id: {{ $.Values.kmsId }}
  {{- end }}
  everest.io/disk-volume-type: {{ $diskTypeValues.reclaimPolicy }}
  everest.io/passthrough: "true"
provisioner: everest-csi-provisioner
reclaimPolicy: {{ $diskTypeValues.reclaimPolicy }}
volumeBindingMode: Immediate
{{- end }}