{{ range $projectName,$project := .Values.projects }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ $projectName }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
spec:
  generators:
    - list:
        elements:
          - cluster: in-cluster
            url: "https://kubernetes.default.svc"
  template:
    metadata:
      name: {{ $projectName }}
    spec:
      project: {{ $projectName }}
      revisionHistoryLimit: 3
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true
          {{- if $project.serverSideApply}}
          - ServerSideApply=true
          {{- end}}
      destination:
        server: https://kubernetes.default.svc
        namespace: {{ $.Release.Namespace }}
      source:
        path: {{ $project.git.path | default $projectName }}
        repoURL: {{ $project.git.repoUrl }}
        targetRevision: {{ $project.git.branch | default "main" }}
        helm:
          values: |
            projectValues:
              {{- $project.projectValues | toYaml | nindent 14}}
          valueFiles:
            - values.yaml
            {{- if ($project.projectValues).stage }}
            - values-{{ $project.projectValues.stage }}.yaml
            {{- end}}
---
{{- end }}
