{{- if ne (.Values.ingressRoute.enabled | toString ) "false" }}
{{- $certSecretName := .Values.ingressRoute.certificate.name | default (printf "%s-%s" .Release.Name "cert")}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}
spec:
  entryPoints:
    - {{.Values.ingressRoute.entryPointName}}
  routes:
    - kind: Rule
      match: Host(`{{ .Values.ingressRoute.domain }}`)
      services:
        - name: {{ .Release.Name }}
          port: {{ .Values.keycloak.service.ports.http }}
  {{- if ne (.Values.ingressRoute.certificate.enabled | toString) "false" }}
  tls:
    secretName: {{ $certSecretName }}
    domains:
      - main: {{ .Values.ingressRoute.domain}}
  {{- end }}
{{- end }}