{{- range $retention := tuple "Retain" "Delete"}}
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  {{- if $.Values.kmsId }}
  name: csi-sfsturbo-{{ lower $retention }}-encrypted
  {{- else }}
  name: csi-sfsturbo-{{ lower $retention }}
  {{- end }}
parameters:
  csi.storage.k8s.io/csi-driver-name: sfsturbo.csi.everest.io
  csi.storage.k8s.io/fstype: nfs
  everest.io/share-expand-type: bandwidth
  everest.io/share-source: sfs-turbo
  everest.io/share-volume-type: STANDARD
  everest.io/zone: eu-de-01
  {{- if $.Values.kmsId }}
  everest.io/crypt-key-id: {{ $.Values.kmsId }}
  {{- end }}
provisioner: everest-csi-provisioner
reclaimPolicy: {{ $retention }}
volumeBindingMode: Immediate
---
{{- end }}