apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-storage-secrets
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
type: Opaque
data:
  S3_BUCKET_NAME: {{ .Values.nextcloudStorage.s3.S3_BUCKET_NAME | b64enc }}
  S3_PUBLIC_KEY: {{ .Values.nextcloudStorage.s3.S3_PUBLIC_KEY | b64enc }}
  S3_SECRET_KEY: {{ .Values.nextcloudStorage.s3.S3_SECRET_KEY | b64enc }}
  S3_BUCKET_URL: {{ .Values.nextcloudStorage.s3.S3_BUCKET_URL | b64enc }}