{{- if ne .Values.ingressRoute.certificate.enabled false }}
{{- $certSecretName := .Values.ingressRoute.certificate.name | default (printf "%s-%s" .Release.Name "cert")}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}
spec:
  secretName: {{ $certSecretName }}
  issuerRef:
    name: {{.Values.ingressRoute.certificate.clusterIssuer}}
    kind: ClusterIssuer
  commonName: {{.Values.ingressRoute.domain}}
  privateKey:
    algorithm: "RSA"
    size: 4096
  dnsNames:
    - {{.Values.ingressRoute.domain}}
{{- end }}