{{- if ne .Values.ingressRoute.enabled false }}
{{- $certSecretName := .Values.ingressRoute.certificate.name | default (printf "%s-%s" .Release.Name "cert")}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}
spec:
  entryPoints:
    - {{.Values.ingressRoute.entryPointName}}
  routes:
    - kind: Rule
      match: Host(`{{ .Values.ingressRoute.domain }}`)
      middlewares:
        - name: basic-auth-gateway
      services:
        - name: {{ .Values.ingressRoute.upstream.service.name }}
          port: {{ .Values.ingressRoute.upstream.service.port }}
  {{- if ne .Values.ingressRoute.certificate.enabled false }}
  tls:
    secretName: {{ $certSecretName }}
    domains:
      - main: {{ .Values.ingressRoute.domain}}
  {{- end }}
{{- end }}