{{ if and (eq .Values.clusterIssuers.otcDNS.enabled true) (eq .Values.clusterIssuers.otcDNS.existingSecretRef "") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-otc-dns-creds
stringData:
  accessKey: {{ .Values.clusterIssuers.otcDNS.accessKey | quote }}
  secretKey: {{ .Values.clusterIssuers.otcDNS.secretKey | quote }}
{{ end }}
