{{ if and (eq .Values.clusterIssuers.otcDNS.enabled true) (eq .Values.clusterIssuers.otcDNS.existingSecretRef "") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-otc-dns-creds
stringData:
  accessKey: {{ .Values.clusterIssuers.otcDNS.accessKey | quote }}
  secretKey: {{ .Values.clusterIssuers.otcDNS.secretKey | quote }}
{{ end }}
---
{{- with .Values.externalSecret }}
{{- if .enabled }}
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ $.Release.Name }}-otc-dns-creds
spec:
  selector:
    secret:
      name: {{ $.Release.Name }}-otc-dns-creds
  {{- with .push.spec.refreshInterval }}
  refreshInterval: {{ . }}
  {{- end }}
  {{- with .push.spec.deletionPolicy }}
  deletionPolicy: {{ . }}
  {{- end }}
  {{- with .push.spec.updatePolicy }}
  updatePolicy: {{ . }}
  {{- end }}
  secretStoreRefs:
  {{- if .push.secretStores }}
    {{ range $secretStore := .push.secretStores }}
    - {{ $secretStore | toYaml | nindent 6 }}
    {{- end }}
  {{- else }}
    {{- with $.Values.externalSecret.secretStore }}
    - {{ toYaml . | nindent 6 | trim }}
    {{- end }} 
  {{- end }} 
  data:
  {{- range .push.remoteRef.keys }}
  - match:
      secretKey: {{ . }}
      remoteRef:
        remoteKey: cert_manager
        property: {{ . }}
  {{- end }}
{{- end }}
{{- end }}