{{ if eq .Values.clusterIssuer.http01.enabled true }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{.Values.clusterIssuer.http01.name}}
spec:
  acme:
    email: {{ .Values.clusterIssuer.email | required "clusterIssuer.email is not set" }}
{{ if eq .Values.clusterIssuer.useStaging false }}
    server: https://acme-v02.api.letsencrypt.org/directory
{{ else }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
{{ end }}
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: {{.Values.clusterIssuer.http01.name}}

    solvers:
      # Add a single challenge solver, HTTP01 using an Ingress
      - http01:
          ingress:
            ingressTemplate:
              metadata:
                annotations:
                  "cert-manager.io/issue-temporary-certificate": "true"
                  "kubernetes.io/ingress.class": {{.Values.clusterIssuer.http01.ingressClass}}
                  "certmanager.k8s.io/issuer": letsencrypt
{{ end }}