{{- range $issuerName, $issuer := .Values.clusterIssuers.http | default dict }}
{{- if eq $issuer.enabled true }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{$issuerName}}
  {{- with $issuer.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  acme:
    email: {{ $.Values.clusterIssuers.email }}
    server: {{ $issuer.server }}
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: {{$issuerName}}

    solvers:
      # Add a single challenge solver, HTTP01 using an Ingress
      - http01:
          ingress:
            ingressTemplate:
              metadata:
                annotations:
                  "kubernetes.io/ingress.class": {{$issuer.ingressClass}}
---
{{- end }}
{{- end }}
