{{- with .Values.externalSecret }}
{{- if and .enabled .push.enabled (not .pull.enabled) }}
{{ $spec := .push.spec  }}
{{- range $secretName, $secretConfig := .push.secrets }}
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ $secretName }}
spec:
  selector:
    secret:
      name: {{ $secretName }}
  {{- with $spec.refreshInterval }}
  refreshInterval: {{ . }}
  {{- end }}
  {{- with $spec.deletionPolicy }}
  deletionPolicy: {{ . }}
  {{- end }}
  {{- with $spec.updatePolicy }}
  updatePolicy: {{ . }}
  {{- end }}
  secretStoreRefs:
  {{- if $spec.secretStores }}
    {{ range $secretStore := $spec.secretStores }}
    - {{ $secretStore | toYaml | nindent 6 }}
    {{- end }}
  {{- else }}
    {{- with $.Values.externalSecret.secretStore }}
    - {{ toYaml . | nindent 6 | trim }}
    {{- end }} 
  {{- end }} 
  data:
  {{- range $secretConfig.keys }}
  - match:
      secretKey: {{ . | quote }}
      remoteRef:
        remoteKey: {{ $secretConfig.path | quote }}
        property: {{ . | quote }}
  {{- end }}
{{- end }}
{{- end }}
{{- if and .enabled .pull.enabled }}
---
{{ $spec := .pull.spec  }}
{{- range $secretName, $secretConfig := .pull.secrets }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $secretName }}
spec:
  refreshInterval: {{ $spec.refreshInterval }}
  target:
    name: {{ $secretName }}
    creationPolicy: {{ $spec.creationPolicy }}
    deletionPolicy: {{ $spec.deletionPolicy }}
  secretStoreRef:
  {{- with $.Values.externalSecret.secretStore }}
    {{ toYaml . | nindent 4 | trim }}
  {{- end }}
  data:
  {{- range $secretConfig.keys }}
    - secretKey: {{ . | quote }}
      remoteRef:
        key: {{ $secretConfig.path | quote }}
        property: {{ . | quote }}
  {{- end }}
---
{{- end }}
{{- end }}
{{- end }}