{{ with .Values.policyException }}
{{ if tpl .enabled $ | toString | eq "true" }}
apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: cert-manager-webhook
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
spec:
  exceptions:
    - policyName: require-run-as-nonroot
      ruleNames:
        - run-as-non-root
    - policyName: enforce-security-context
      ruleNames:
        - add-pod-security-context
  match:
    any:
      - resources:
          kinds:
            - Pod
          names:
            - '*cert-manager-webhook-opentelekomcloud*'
          namespaces:
            - {{ $.Release.Namespace }}
{{- end }}
{{- end }}
