{{- with .Values.externalSecret }}
{{- if and .enabled .push.enabled }}
{{ $spec := .push.spec }}
{{- range $secretName, $secretConfig := .push.secrets }}
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ $secretName }}
spec:
  selector:
    secret:
      name: {{ $secretName }}
  refreshInterval: {{ $spec.refreshInterval }}
  deletionPolicy: {{ $spec.deletionPolicy }}
  updatePolicy: {{ $spec.updatePolicy }}
  secretStoreRefs:
  {{- if $spec.secretStores }}
    {{- range $secretStore := $spec.secretStores }}
    - {{ toYaml $secretStore | nindent 6 | trim }}
    {{- end }}
  {{- else }}
    - kind: {{ $.Values.externalSecret.secretStore.kind }}
      name: {{ $.Values.externalSecret.secretStore.name }}
  {{- end }} 
  data:
  {{- range $secretConfig.keys }}
  - match:
      secretKey: {{ .name | quote }}
      remoteRef:
        remoteKey: {{ required "Path to push secret is required" $secretConfig.path | quote }}
        property: {{ .remoteKey | default .name | quote }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}