apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Release.Name}}-index-pattern-init-config
data:
  index-pattern-init.sh: |
    #!/bin/sh

    KIBANA_BASE_PATH="{{ .Values.ingress.kibana.path }}"

{{- range $indexName,$indexValues  := .Values.indexPatternInit.indices }}
    # Apply default Index Pattern into Kibana
    echo "create index pattern {{$indexName}}"
    curl -u "$ELASTICSEARCH_USERNAME:$ELASTICSEARCH_PASSWORD" --cacert /kb-cert/ca.crt -X POST -v https://$KIBANA_ENDPOINT$KIBANA_BASE_PATH/api/index_patterns/index_pattern -H 'kbn-xsrf: true' -H 'Content-Type: application/json' -d '{"index_pattern": { "id": "{{$indexName}}", "title": "{{ coalesce $indexValues.index (printf "%s*" $indexName) }}","timeFieldName": "{{$indexValues.timestampField}}"},"override":true,"refresh_fields":true}'
    echo "create index pattern {{$indexName}} finished"
{{ end }}
