apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Release.Name}}-index-pattern-init-config
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
data:
  index-pattern-init.sh: |
    #!/bin/sh

    KIBANA_BASE_PATH="{{ .Values.ingress.kibana.path }}"

{{- range $indexName,$indexValues  := .Values.indexPatternInit.indices }}
    # Create Data View in Kibana using new Data Views API
    echo "create data view {{$indexName}}"
    curl -u "$ELASTICSEARCH_USERNAME:$ELASTICSEARCH_PASSWORD" \
      --cacert /kb-cert/ca.crt \
      -X POST -v \
      "https://$KIBANA_ENDPOINT$KIBANA_BASE_PATH/api/data_views/data_view" \
      -H 'kbn-xsrf: true' \
      -H 'Content-Type: application/json' \
      -d '{
        "data_view": {
          "title": "{{ coalesce $indexValues.index (printf "%s*" $indexName) }}",
          {{- if $indexValues.name }}
          "name": "{{ $indexValues.name }}",
          {{- end }}
          "timeFieldName": "{{$indexValues.timestampField}}"
        },
        "override": true
      }'
    echo ""
    echo "create data view {{$indexName}} finished"
{{ end }}
