{{- with .Values.indexPatternInit }}

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $.Release.Name }}-index-pattern-init
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    checksum/config: {{ include (print $.Template.BasePath "/index-pattern-init/config.yaml") $ | sha256sum | substr 0 50 }}
spec:
  backoffLimit: 0
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: {{ $.Release.Name }}-jobcommand
    spec:
      tolerations: {{ .tolerations | toYaml | nindent 8  }}
      nodeSelector: {{ .nodeSelector | toYaml | nindent 8 }}
      restartPolicy: Never
      containers:
        - name: {{ $.Release.Name }}-index-pattern-init
          image: {{ .image.repository }}:{{ .image.tag }}
          imagePullPolicy: IfNotPresent
          command: [ '/bin/sh', '-c' ]
          args: [ "/index-pattern-init-config/index-pattern-init.sh" ]
          env:
            - name: ELASTICSEARCH_USERNAME
              value: elastic
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: elastic
                  name: {{ $.Release.Name }}-es-elastic-user
            - name: KIBANA_ENDPOINT
              value: {{ $.Release.Name }}-kb-http:5601
          volumeMounts:
            - name: index-pattern-init-config
              mountPath: /index-pattern-init-config
            - name: kibana-certificate
              mountPath: /kb-cert
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            runAsUser: {{ .image.userId }}
      volumes:
        - name: index-pattern-init-config
          configMap:
            name: {{ $.Release.Name }}-index-pattern-init-config
            defaultMode: 0755
        - name: kibana-certificate
          secret:
            secretName: {{ $.Release.Name }}-kb-http-certs-public
      securityContext:
        fsGroup: 1001
        runAsGroup: 1002
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
        runAsUser: {{ .image.userId }}
  {{- end }}
