{{- if eq .Values.ollama.ingress.traefikMiddlewareEnabled "true" }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix-ollama
spec:
  stripPrefix:
    prefixes:
      - "/ollama"
{{- end }}