cert-manager:
  extraArgs:
    - --logging-format=json

  cainjector:
    extraArgs:
      - --logging-format=json

  webhook:
    extraArgs:
      - --logging-format=json

  startupapicheck:
    extraArgs:
      - --logging-format=json

  prometheus:
    enabled: true
    servicemonitor:
      enabled: true


cert-manager-webhook-opentelekomcloud:
  groupName: acme.opentelekomcloud.com
# Create base clusterissuers with most frequently used configuration
clusterIssuers:
  # -- (string) Required, replace with the e-mails you want to receive the warnings
  # You must replace this email address with your own.
  # Let's Encrypt will use this to contact you about expiring
  # certificates, and issues related to your account.
  email:
  http:
    enabled: true
    name: letsencrypt
    ingressClass: traefik
    server: https://acme-v02.api.letsencrypt.org/directory

  # -- Only available for OTC
  otcDNS:
    enabled: true
    # Name of an existing secret to use, otherwise will create one with the content of "accessKey" and "secretKey"
    # Existing secret has to have the keys "accessKey" and "secretKey" specified with appropriate values
    existingSecretRef: ""
    name: letsencrypt-dns
    server: https://acme-v02.api.letsencrypt.org/directory
    region: eu-de
    # Optional, if existingSecretRef is used
    accessKey: ""
    secretKey: ""

externalSecret:
  enabled: false
  
  secretStore:
    # Valid values: ClusterSecretStore or SecretStore
    kind: ClusterSecretStore
    name: "vault"
  
  # -- Creates a PushSecret resource. It describes what data should be pushed to the SecretStore. This will be created also when pull is set to false.
  push:
    enabled: false
    spec:
      # If set, .externalSecrets.secretStore will be ignored
      secretStores: []
      # - kind: ClusterSecretStore
      #   name: "MySuperSecretStore"
      #   # labelSelector: ...
      #   #  matchExpressions: []
      #   #  matchLabels: {}

      # Deletion Policy to handle Secrets in the provider
      # Valid values: Delete, None
      deletionPolicy: Delete

      # The Interval to which External Secrets will try to push a secret definition
      refreshInterval: 1h

      # UpdatePolicy to handle Secrets in the provider
      # Valid values: Replace, IfNotExists
      updatePolicy: IfNotExists
 
    secrets: {}
      # <secret-name>:
      #   path: ""
      #   keys: # list which is afterwards used 1:1 inside the template
      #   - name: accessKey
      #     remoteKey: access_key # optional, if not specified "name" is used
      #   - name: secretKey
      #     remoteKey: secret_key # optional, if not specified "name" is used

  # -- Create ExternalSecret resources. It describes what data should be fetched, how the data should be transformed and saved as a Kind=Secret.
  pull:
    enabled: false
    spec:
      # RefreshInterval is the amount of time before the values are read again from the SecretStore provider
      # Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h"
      # Example values: "1h", "2h30m", "10s"
      # May be set to zero to fetch and create it once
      refreshInterval: 1m

      # CreationPolicy defines rules on how to create the resulting Secret.
      # Owner, Orphan, Merge, None
      creationPolicy: Owner

      # DeletionPolicy defines rules on how to delete the resulting Secret
      # Valid values: Delete, Merge, Retain
      deletionPolicy: Delete
      # Strategy for converting secret key names before matching and rewriting. Can be Default, Unicode or ReverseUnicode. Defaults to Default
      conversionStrategy: Default
      # Set the following Decoding Strategies based on the need. Can be None, Base64, Base64URL or Auto. Defaults to None
      decodingStrategy: None
      # Policy for fetching tags/labels from provider secrets, possible options are Fetch, None. Defaults to None
      metadataPolicy: None
    
    secrets: {}
      # <secret-name>:
      #   path: ""
      #   conversionStrategy: Default # optional, if not specified, the common from .spec field is used
      #   decodingStrategy:  None # optional, if not specified, the common from .spec field is used
      #   metadataPolicy:  None # optional, if not specified, the common from .spec field is used
      #   keys: # list which is afterwards used 1:1 inside the template
      #   - name: accessKey
      #     remoteKey: access_key # optional, if not specified "name" is used
      #   - name: secretKey
      #     remoteKey: secret_key # optional, if not specified "name" is used

policyException:
  # Only enabled if clusterIssuers.otcDNS.enabled is also true
  enabled: "{{ .Values.clusterIssuers.otcDNS.enabled }}"