cert-manager:
  extraArgs:
    - --logging-format=json

  cainjector:
    extraArgs:
      - --logging-format=json

  webhook:
    extraArgs:
      - --logging-format=json

  startupapicheck:
    extraArgs:
      - --logging-format=json

  prometheus:
    enabled: true
    servicemonitor:
      enabled: true


cert-manager-webhook-opentelekomcloud:
  groupName: acme.opentelekomcloud.com
# Create base clusterissuers with most frequently used configuration
clusterIssuers:
  # -- (string) Required, replace with the e-mails you want to receive the warnings
  # You must replace this email address with your own.
  # Let's Encrypt will use this to contact you about expiring
  # certificates, and issues related to your account.
  email:
  http:
    enabled: true
    name: letsencrypt
    ingressClass: traefik
    server: https://acme-v02.api.letsencrypt.org/directory

  # -- Only available for OTC
  otcDNS:
    enabled: true
    # Name of an existing secret to use, otherwise will create one with the content of "accessKey" and "secretKey"
    # Existing secret has to have the keys "accessKey" and "secretKey" specified with appropriate values
    existingSecretRef: ""
    name: letsencrypt-dns
    server: https://acme-v02.api.letsencrypt.org/directory
    region: eu-de
    # Optional, if existingSecretRef is used
    accessKey: ""
    secretKey: ""


policyException:
  # Only enabled if clusterIssuers.otcDNS.enabled is also true
  enabled: "{{ .Values.clusterIssuers.otcDNS.enabled }}"