{{- with .Values.externalSecret }}
{{- if .enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $.Release.Name }}-secrets
spec:
  refreshInterval: {{ .refreshInterval }}
  target:
    name: {{ $.Release.Name }}-secrets
    creationPolicy: {{ .pull.spec.creationPolicy }}
    deletionPolicy: {{ .pull.spec.deletionPolicy }}
  secretStoreRef:
  {{- with $.Values.externalSecret.secretStore }}
    {{ toYaml . | nindent 4 | trim }}
  {{- end }}
  data:
  {{- range $property, $values := .pull.paths }}
    - secretKey: {{ $property | quote }}
      remoteRef:
        key: {{ $values.path | quote }}
        property: {{ $values.key | quote }}
  {{- end }}
{{- end }}
{{- end }}
