{{- if .Values.ingress.elasticsearch -}}
{{- with .Values.ingress.elasticsearch }}
{{- if eq .enabled true }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Release.Name }}-elasticsearch
  {{- with .labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
spec:
  {{ if .className }}
  ingressClassName: {{ .className }}
  {{- end }}

  tls:
    - hosts:
      - {{ .host }}

  rules:
    - host: {{ .host }}
      http:
        paths:
          - path: {{ .path }}
            pathType: "Prefix"
            backend:
              service:
                name: {{ $.Release.Name }}-es-http
                port:
                  name: "https"
{{- end }}
{{- end }}
{{- end }}
