{{- with .Values.ingress.elasticsearch -}}
{{- if eq .enabled true }}
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: {{ $.Release.Name }}-elasticsearch
spec:
  serverName: {{ $.Release.Name }}-es-http
  rootCAsSecrets:
    - {{ $.Release.Name }}-es-http-certs-public
{{- end }}
{{- end }}
