{{- range $roleName, $roleDescription := .Values.auth.roles }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-role-{{ kebabcase $roleName }}
type: Opaque
stringData:
  roles.yml: |-
    {{ $roleName }}:
{{ $roleDescription | toYaml | nindent 6 }}

---
{{ end }}
