{{- range $userName, $userDescription := .Values.auth.users }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-user-{{ kebabcase $userName }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ $userName | quote }}
{{- if (not (empty $userDescription.existingPassword)) }}
  password: {{ $userDescription.existingPassword }}
{{- end }}
  roles: {{ join "," $userDescription.roles }}

---
{{ end }}
