name: Release Charts

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - "*"
      - '!master'
env:
  HELM_VERSION: v3.4.0

jobs:
  find-charts:
    name: Find Charts
    container: debian:buster-slim
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.determine-chart-names.outputs.matrix }}
    steps:
      - uses: actions/checkout@v1
      - id: determine-chart-names
        run: echo "matrix=[$(ls -Q --format=commas ./charts)]" >> $GITHUB_OUTPUT
  release-charts:
    name: Release
    needs: find-charts
    strategy:
      matrix:
        chart: ${{fromJSON(needs.find-charts.outputs.matrix)}}
    permissions:
      contents: write
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Lint ${{ matrix.chart }}
        run: helm lint charts/${{ matrix.chart }} --strict

      - name: KubeVal ${{ matrix.chart }}
        run: |
          helm plugin install https://github.com/instrumenta/helm-kubeval
          helm kubeval --ignore-missing-schemas charts/${{ matrix.chart }}


      - name: Trivy Scan ${{ matrix.chart }}
        uses: aquasecurity/trivy-action@0.10.0
        with:
          scan-type: 'config'
          hide-progress: false
          format: 'sarif'
          scan-ref: 'charts/${{matrix.chart}}'
          output: 'trivy-results.sarif'
          exit-code: '1'
          ignore-unfixed: false
          severity: 'MEDIUM,HIGH,CRITICAL'
          limit-severities-for-sarif: true

      - name: Upload Trivy scan results for ${{ matrix.chart }}
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

