{{- with .Values.kibana }}
{{- if .enabled }}

apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: {{ $.Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  version: {{ tpl .version $ }}
  count: {{ .count }}
  {{- with $.Values.ingress.kibana}}
    {{- if and (eq .enabled true) (eq .className "traefik") }}
  http:
    service:
      metadata:
        annotations:
          traefik.ingress.kubernetes.io/service.serverstransport: "{{ $.Release.Namespace }}-{{ $.Release.Name }}-kibana@kubernetescrd"
          traefik.ingress.kubernetes.io/service.serversscheme: "https"
    {{- end }}
  {{- end }}
  elasticsearchRef:
    name: {{ $.Release.Name }}
  config:
    {{- tpl (.config | toYaml) $ | nindent 4 }}
  podTemplate:
    metadata:
      annotations:
        checksum/users: {{ include (print $.Template.BasePath "/eks-stack/elasticsearch-users.yaml") $ | sha256sum | substr 0 50 }}
        checksum/roles: {{ include (print $.Template.BasePath "/eks-stack/elasticsearch-roles.yaml") $ | sha256sum | substr 0 50 }}
    spec:
      {{- tpl (.podTemplateSpec | toYaml) $ | nindent 6 }}
{{- end }}
{{- end }}
