{{- with .Values.logstash}}
{{- if .enabled }}
apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: {{ $.Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  count: 2
  version: {{  tpl .version $ }}
  elasticsearchRefs: 
    {{- tpl (toYaml .elasticsearchRefs) $ | nindent 4 }} 
  config: 
    {{- toYaml .config | nindent 4 }}
  pipelines:
    {{- toYaml .pipelines | nindent 2 }}
  podTemplate:
    metadata:
      annotations:
        checksum/users: {{ include (print $.Template.BasePath "/eks-stack/elasticsearch-users.yaml") $ | sha256sum | substr 0 50 }}
    spec:
      securityContext:
        runAsUser: 0
      {{- if .tolerations }}
      tolerations:
        {{- .tolerations | toYaml | indent 10 }}
      {{- end }}
      containers:
      - name: logstash
        resources:
          {{- .resources | toYaml | nindent 12}}
        env:
          {{- tpl (.env | toYaml) $ | nindent 10 }}
          {{- if .extraEnv }}
            {{- .extraEnv | toYaml | nindent 10 }}
          {{- end }}
        volumeMounts:
          {{- .volumeMounts | toYaml | nindent 10}}
          {{- if .extraVolumeMounts }}
            {{- .extraVolumeMounts | toYaml | nindent 10 }}
          {{- end }}
      volumes:
        {{- .volumes | toYaml | nindent 8 }}
        {{- if .extraVolumes }}
          {{- .extraVolumes | toYaml | nindent 8 }}
        {{- end -}}
{{- end -}}
{{- end -}}
