{{- if .Values.dbInit.postgres.enabled }}
{{- with .Values.dbInit.postgres }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .name }}
  annotations:
    dbChecksum: {{ .databases | toString | sha256sum}}
    sqlScriptChecksum: {{.script | toString | sha256sum}}
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "-5"
  labels: {{ toYaml .labels | nindent 4 }}
spec:
  backoffLimit: 0
  parallelism: 1
  completions: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: {{ .name }}
          image: {{ .image.repository }}:{{.image.tag}}
          imagePullPolicy: {{.image.pullPolicy}}
          command: [ "/bin/sh", "-c" ]
          args:
            - >
              psql -f /initdb/init.sql
          env:
            {{- range $key, $value := .env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          volumeMounts:
            - name: {{.name}}
              mountPath: /initdb
      volumes:
        - name: {{.name}}
          secret:
            secretName: {{.name}}
{{- end }}
{{- end }}