apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      release: {{ .Chart.Name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        release: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{  .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ default "IfNotPresent" }}
          ports:
            {{- range $mapping := .Values.mappings }}
          - containerPort: {{ $mapping.port }}
          args:
            - tcp-listen:{{ $mapping.port }},fork,reuseaddr
            - tcp-connect:{{ $mapping.talk }}:{{ $mapping.talkToPort }}
            {{- end }}